config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  acts_as_votable
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show

  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Successfully Created New Pin"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was Successfully Updated"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  private
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Pinterest", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "New Pin", new_pin_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Account", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { multipart: true }) do |f| %>
  <% if @pin.errors.any? %>
    <div id="erros">
      <h2>
        <%= pluralize(@pin.error.count, "error") %>
        prevented this pin from saving
      </h2>

      <ul>
        <%= @pin.erros.full_message.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :image, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>
  <%= f.button :submit, class: 'btn btn-primary' %>
 <% end %>

app/views/pins/edit.html.erb
<div id="edit_page" class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Pin</h1>
      </div>
      <div class="panel-body">
        <div class="current-image">
          <strong class="center">
            Current image
          </strong>
          <%= image_tag @pin.image.url(:medium) %>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to(image_tag(pin.image.url), pin) %>
      <div class="panel-body">
        <h2><%= link_to pin.title, pin %></h2>
        <p class="user">
          Submitted by <%= pin.user.email %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<div id="new_page" class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Create New Pin</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div id="pin_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url %>
      </div>
      <div class="panel-body">
        <h1><%= @pin.title %></h1>
        <p class="description"><%= @pin.description %></p>
        <p>Submitted by: <%= @pin.user.email %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            Submitted by: <%= @pin.user.email %>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to like_pin_path(@pin), method: :put, class: 'btn btn-default' do %>
                <span class="glyphicon glyphicon-heart"></span>
                <%= @pin.get_upvotes.size %>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to "Edit", edit_pin_path, class: 'btn btn-default' %>
                <%= link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-default' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>